# easy cells
# writed by Edwin Saul https://edwinsaul.com

styles={
        # aligment
        "left"       :{"align":"left"},
        "right"      :{"align":"right"},
        "center"     :{"align":"center"},
        "justify"    :{"align":"justify"},
        "vcenter"    :{"valign":"vcenter"},
        "vjustify"   :{"align":"vjustify"},
        "top"        :{"valign":"top"},
        "bottom"     :{"valign":"bottom"},

        # basic font types
        "bold"       :{"bold":True},
        "italic"     :{"italic":True},
        "underline"  :{"underline":True},

        #extra format 
        "lock"       :{"locked":True},
        "hide"       :{"hidden":True},

        #cell border
        "l-top"       :{"top":True},
        "l-bottom"    :{"bottom":True},
        "l-left"      :{"left":True},
        "l-right"     :{"right":True},

        "no_box"        :{"border":0},
        "box"           :{"border":1},
        "boxContinuous" :{"border":2},
        "boxDash"       :{"border":3},
        "boxDot"        :{"border":4},
        "box2"          :{"border":2},
        "box3"          :{"border":3},
        "box4"          :{"border":4},

        # border color
        "l-aliceblue"               : {"border_color" : "#f0f8ff"},
        "l-antiquewhite"            : {"border_color" : "#faebd7"},
        "l-aqua"                    : {"border_color" : "#00ffff"},
        "l-aquamarine"              : {"border_color" : "#7fffd4"},
        "l-azure"                   : {"border_color" : "#f0ffff"},
        "l-beige"                   : {"border_color" : "#f5f5dc"},
        "l-bisque"                  : {"border_color" : "#ffe4c4"},
        "l-black"                   : {"border_color" : "#000000"},
        "l-blanchedalmond"          : {"border_color" : "#ffebcd"},
        "l-blue"                    : {"border_color" : "#0000ff"},
        "l-blueviolet"              : {"border_color" : "#8a2be2"},
        "l-brown"                   : {"border_color" : "#a52a2a"},
        "l-burlywood"               : {"border_color" : "#deb887"},
        "l-cadetblue"               : {"border_color" : "#5f9ea0"},
        "l-chartreuse"              : {"border_color" : "#7fff00"},
        "l-chocolate"               : {"border_color" : "#d2691e"},
        "l-coral"                   : {"border_color" : "#ff7f50"},
        "l-cornflowerblue"          : {"border_color" : "#6495ed"},
        "l-cornsilk"                : {"border_color" : "#fff8dc"},
        "l-crimson"                 : {"border_color" : "#dc143c"},
        "l-cyan"                    : {"border_color" : "#00ffff"},
        "l-darkblue"                : {"border_color" : "#00008b"},
        "l-darkcyan"                : {"border_color" : "#008b8b"},
        "l-darkgoldenrod"           : {"border_color" : "#b8860b"},
        "l-darkgray"                : {"border_color" : "#a9a9a9"},
        "l-darkgreen"               : {"border_color" : "#006400"},
        "l-darkgrey"                : {"border_color" : "#a9a9a9"},
        "l-darkkhaki"               : {"border_color" : "#bdb76b"},
        "l-darkmagenta"             : {"border_color" : "#8b008b"},
        "l-darkolivegreen"          : {"border_color" : "#556b2f"},
        "l-darkorange"              : {"border_color" : "#ff8c00"},
        "l-darkorchid"              : {"border_color" : "#9932cc"},
        "l-darkred"                 : {"border_color" : "#8b0000"},
        "l-darksalmon"              : {"border_color" : "#e9967a"},
        "l-darkseagreen"            : {"border_color" : "#8fbc8f"},
        "l-darkslateblue"           : {"border_color" : "#483d8b"},
        "l-darkslategray"           : {"border_color" : "#2f4f4f"},
        "l-darkslategrey"           : {"border_color" : "#2f4f4f"},
        "l-darkturquoise"           : {"border_color" : "#00ced1"},
        "l-darkviolet"              : {"border_color" : "#9400d3"},
        "l-deeppink"                : {"border_color" : "#ff1493"},
        "l-deepskyblue"             : {"border_color" : "#00bfff"},
        "l-dimgray"                 : {"border_color" : "#696969"},
        "l-dimgrey"                 : {"border_color" : "#696969"},
        "l-dodgerblue"              : {"border_color" : "#1e90ff"},
        "l-firebrick"               : {"border_color" : "#b22222"},
        "l-floralwhite"             : {"border_color" : "#fffaf0"},
        "l-forestgreen"             : {"border_color" : "#228b22"},
        "l-fuchsia"                 : {"border_color" : "#ff00ff"},
        "l-gainsboro"               : {"border_color" : "#dcdcdc"},
        "l-ghostwhite"              : {"border_color" : "#f8f8ff"},
        "l-gold"                    : {"border_color" : "#ffd700"},
        "l-goldenrod"               : {"border_color" : "#daa520"},
        "l-gray"                    : {"border_color" : "#808080"},
        "l-green"                   : {"border_color" : "#008000"},
        "l-greenyellow"             : {"border_color" : "#adff2f"},
        "l-grey"                    : {"border_color" : "#808080"},
        "l-honeydew"                : {"border_color" : "#f0fff0"},
        "l-hotpink"                 : {"border_color" : "#ff69b4"},
        "l-indianred"               : {"border_color" : "#cd5c5c"},
        "l-indigo"                  : {"border_color" : "#4b0082"},
        "l-ivory"                   : {"border_color" : "#fffff0"},
        "l-khaki"                   : {"border_color" : "#f0e68c"},
        "l-lavender"                : {"border_color" : "#e6e6fa"},
        "l-lavenderblush"           : {"border_color" : "#fff0f5"},
        "l-lawngreen"               : {"border_color" : "#7cfc00"},
        "l-lemonchiffon"            : {"border_color" : "#fffacd"},
        "l-lightblue"               : {"border_color" : "#add8e6"},
        "l-lightcoral"              : {"border_color" : "#f08080"},
        "l-lightcyan"               : {"border_color" : "#e0ffff"},
        "l-lightgoldenrodyellow"    : {"border_color" : "#fafad2"},
        "l-lightgray"               : {"border_color" : "#d3d3d3"},
        "l-lightgreen"              : {"border_color" : "#90ee90"},
        "l-lightgrey"               : {"border_color" : "#d3d3d3"},
        "l-lightpink"               : {"border_color" : "#ffb6c1"},
        "l-lightsalmon"             : {"border_color" : "#ffa07a"},
        "l-lightseagreen"           : {"border_color" : "#20b2aa"},
        "l-lightskyblue"            : {"border_color" : "#87cefa"},
        "l-lightslategray"          : {"border_color" : "#778899"},
        "l-lightslategrey"          : {"border_color" : "#778899"},
        "l-lightsteelblue"          : {"border_color" : "#b0c4de"},
        "l-lightyellow"             : {"border_color" : "#ffffe0"},
        "l-lime"                    : {"border_color" : "#00ff00"},
        "l-limegreen"               : {"border_color" : "#32cd32"},
        "l-linen"                   : {"border_color" : "#faf0e6"},
        "l-magenta"                 : {"border_color" : "#ff00ff"},
        "l-maroon"                  : {"border_color" : "#800000"},
        "l-mediumaquamarine"        : {"border_color" : "#66cdaa"},
        "l-mediumblue"              : {"border_color" : "#0000cd"},
        "l-mediumorchid"            : {"border_color" : "#ba55d3"},
        "l-mediumpurple"            : {"border_color" : "#9370db"},
        "l-mediumseagreen"          : {"border_color" : "#3cb371"},
        "l-mediumslateblue"         : {"border_color" : "#7b68ee"},
        "l-mediumspringgreen"       : {"border_color" : "#00fa9a"},
        "l-mediumturquoise"         : {"border_color" : "#48d1cc"},
        "l-mediumvioletred"         : {"border_color" : "#c71585"},
        "l-midnightblue"            : {"border_color" : "#191970"},
        "l-mintcream"               : {"border_color" : "#f5fffa"},
        "l-mistyrose"               : {"border_color" : "#ffe4e1"},
        "l-moccasin"                : {"border_color" : "#ffe4b5"},
        "l-navajowhite"             : {"border_color" : "#ffdead"},
        "l-navy"                    : {"border_color" : "#000080"},
        "l-oldlace"                 : {"border_color" : "#fdf5e6"},
        "l-olive"                   : {"border_color" : "#808000"},
        "l-olivedrab"               : {"border_color" : "#6b8e23"},
        "l-orange"                  : {"border_color" : "#ffa500"},
        "l-orangered"               : {"border_color" : "#ff4500"},
        "l-orchid"                  : {"border_color" : "#da70d6"},
        "l-palegoldenrod"           : {"border_color" : "#eee8aa"},
        "l-palegreen"               : {"border_color" : "#98fb98"},
        "l-paleturquoise"           : {"border_color" : "#afeeee"},
        "l-palevioletred"           : {"border_color" : "#db7093"},
        "l-papayawhip"              : {"border_color" : "#ffefd5"},
        "l-peachpuff"               : {"border_color" : "#ffdab9"},
        "l-peru"                    : {"border_color" : "#cd853f"},
        "l-pink"                    : {"border_color" : "#ffc0cb"},
        "l-plum"                    : {"border_color" : "#dda0dd"},
        "l-powderblue"              : {"border_color" : "#b0e0e6"},
        "l-purple"                  : {"border_color" : "#800080"},
        "l-red"                     : {"border_color" : "#ff0000"},
        "l-rosybrown"               : {"border_color" : "#bc8f8f"},
        "l-royalblue"               : {"border_color" : "#4169e1"},
        "l-saddlebrown"             : {"border_color" : "#8b4513"},
        "l-salmon"                  : {"border_color" : "#fa8072"},
        "l-sandybrown"              : {"border_color" : "#f4a460"},
        "l-seagreen"                : {"border_color" : "#2e8b57"},
        "l-seashell"                : {"border_color" : "#fff5ee"},
        "l-sienna"                  : {"border_color" : "#a0522d"},
        "l-silver"                  : {"border_color" : "#c0c0c0"},
        "l-skyblue"                 : {"border_color" : "#87ceeb"},
        "l-slateblue"               : {"border_color" : "#6a5acd"},
        "l-slategray"               : {"border_color" : "#708090"},
        "l-slategrey"               : {"border_color" : "#708090"},
        "l-snow"                    : {"border_color" : "#fffafa"},
        "l-springgreen"             : {"border_color" : "#00ff7f"},
        "l-steelblue"               : {"border_color" : "#4682b4"},
        "l-tan"                     : {"border_color" : "#d2b48c"},
        "l-teal"                    : {"border_color" : "#008080"},
        "l-thistle"                 : {"border_color" : "#d8bfd8"},
        "l-tomato"                  : {"border_color" : "#ff6347"},
        "l-turquoise"               : {"border_color" : "#40e0d0"},
        "l-violet"                  : {"border_color" : "#ee82ee"},
        "l-wheat"                   : {"border_color" : "#f5deb3"},
        "l-white"                   : {"border_color" : "#ffffff"},
        "l-whitesmoke"              : {"border_color" : "#f5f5f5"},
        "l-yellow"                  : {"border_color" : "#ffff00"},
        "l-yellowgreen"             : {"border_color" : "#9acd32"},

        # font color
        "f-aliceblue"               : {"font_color" : "#f0f8ff"},
        "f-antiquewhite"            : {"font_color" : "#faebd7"},
        "f-aqua"                    : {"font_color" : "#00ffff"},
        "f-aquamarine"              : {"font_color" : "#7fffd4"},
        "f-azure"                   : {"font_color" : "#f0ffff"},
        "f-beige"                   : {"font_color" : "#f5f5dc"},
        "f-bisque"                  : {"font_color" : "#ffe4c4"},
        "f-black"                   : {"font_color" : "#000000"},
        "f-blanchedalmond"          : {"font_color" : "#ffebcd"},
        "f-blue"                    : {"font_color" : "#0000ff"},
        "f-blueviolet"              : {"font_color" : "#8a2be2"},
        "f-brown"                   : {"font_color" : "#a52a2a"},
        "f-burlywood"               : {"font_color" : "#deb887"},
        "f-cadetblue"               : {"font_color" : "#5f9ea0"},
        "f-chartreuse"              : {"font_color" : "#7fff00"},
        "f-chocolate"               : {"font_color" : "#d2691e"},
        "f-coral"                   : {"font_color" : "#ff7f50"},
        "f-cornflowerblue"          : {"font_color" : "#6495ed"},
        "f-cornsilk"                : {"font_color" : "#fff8dc"},
        "f-crimson"                 : {"font_color" : "#dc143c"},
        "f-cyan"                    : {"font_color" : "#00ffff"},
        "f-darkblue"                : {"font_color" : "#00008b"},
        "f-darkcyan"                : {"font_color" : "#008b8b"},
        "f-darkgoldenrod"           : {"font_color" : "#b8860b"},
        "f-darkgray"                : {"font_color" : "#a9a9a9"},
        "f-darkgreen"               : {"font_color" : "#006400"},
        "f-darkgrey"                : {"font_color" : "#a9a9a9"},
        "f-darkkhaki"               : {"font_color" : "#bdb76b"},
        "f-darkmagenta"             : {"font_color" : "#8b008b"},
        "f-darkolivegreen"          : {"font_color" : "#556b2f"},
        "f-darkorange"              : {"font_color" : "#ff8c00"},
        "f-darkorchid"              : {"font_color" : "#9932cc"},
        "f-darkred"                 : {"font_color" : "#8b0000"},
        "f-darksalmon"              : {"font_color" : "#e9967a"},
        "f-darkseagreen"            : {"font_color" : "#8fbc8f"},
        "f-darkslateblue"           : {"font_color" : "#483d8b"},
        "f-darkslategray"           : {"font_color" : "#2f4f4f"},
        "f-darkslategrey"           : {"font_color" : "#2f4f4f"},
        "f-darkturquoise"           : {"font_color" : "#00ced1"},
        "f-darkviolet"              : {"font_color" : "#9400d3"},
        "f-deeppink"                : {"font_color" : "#ff1493"},
        "f-deepskyblue"             : {"font_color" : "#00bfff"},
        "f-dimgray"                 : {"font_color" : "#696969"},
        "f-dimgrey"                 : {"font_color" : "#696969"},
        "f-dodgerblue"              : {"font_color" : "#1e90ff"},
        "f-firebrick"               : {"font_color" : "#b22222"},
        "f-floralwhite"             : {"font_color" : "#fffaf0"},
        "f-forestgreen"             : {"font_color" : "#228b22"},
        "f-fuchsia"                 : {"font_color" : "#ff00ff"},
        "f-gainsboro"               : {"font_color" : "#dcdcdc"},
        "f-ghostwhite"              : {"font_color" : "#f8f8ff"},
        "f-gold"                    : {"font_color" : "#ffd700"},
        "f-goldenrod"               : {"font_color" : "#daa520"},
        "f-gray"                    : {"font_color" : "#808080"},
        "f-green"                   : {"font_color" : "#008000"},
        "f-greenyellow"             : {"font_color" : "#adff2f"},
        "f-grey"                    : {"font_color" : "#808080"},
        "f-honeydew"                : {"font_color" : "#f0fff0"},
        "f-hotpink"                 : {"font_color" : "#ff69b4"},
        "f-indianred"               : {"font_color" : "#cd5c5c"},
        "f-indigo"                  : {"font_color" : "#4b0082"},
        "f-ivory"                   : {"font_color" : "#fffff0"},
        "f-khaki"                   : {"font_color" : "#f0e68c"},
        "f-lavender"                : {"font_color" : "#e6e6fa"},
        "f-lavenderblush"           : {"font_color" : "#fff0f5"},
        "f-lawngreen"               : {"font_color" : "#7cfc00"},
        "f-lemonchiffon"            : {"font_color" : "#fffacd"},
        "f-lightblue"               : {"font_color" : "#add8e6"},
        "f-lightcoral"              : {"font_color" : "#f08080"},
        "f-lightcyan"               : {"font_color" : "#e0ffff"},
        "f-lightgoldenrodyellow"    : {"font_color" : "#fafad2"},
        "f-lightgray"               : {"font_color" : "#d3d3d3"},
        "f-lightgreen"              : {"font_color" : "#90ee90"},
        "f-lightgrey"               : {"font_color" : "#d3d3d3"},
        "f-lightpink"               : {"font_color" : "#ffb6c1"},
        "f-lightsalmon"             : {"font_color" : "#ffa07a"},
        "f-lightseagreen"           : {"font_color" : "#20b2aa"},
        "f-lightskyblue"            : {"font_color" : "#87cefa"},
        "f-lightslategray"          : {"font_color" : "#778899"},
        "f-lightslategrey"          : {"font_color" : "#778899"},
        "f-lightsteelblue"          : {"font_color" : "#b0c4de"},
        "f-lightyellow"             : {"font_color" : "#ffffe0"},
        "f-lime"                    : {"font_color" : "#00ff00"},
        "f-limegreen"               : {"font_color" : "#32cd32"},
        "f-linen"                   : {"font_color" : "#faf0e6"},
        "f-magenta"                 : {"font_color" : "#ff00ff"},
        "f-maroon"                  : {"font_color" : "#800000"},
        "f-mediumaquamarine"        : {"font_color" : "#66cdaa"},
        "f-mediumblue"              : {"font_color" : "#0000cd"},
        "f-mediumorchid"            : {"font_color" : "#ba55d3"},
        "f-mediumpurple"            : {"font_color" : "#9370db"},
        "f-mediumseagreen"          : {"font_color" : "#3cb371"},
        "f-mediumslateblue"         : {"font_color" : "#7b68ee"},
        "f-mediumspringgreen"       : {"font_color" : "#00fa9a"},
        "f-mediumturquoise"         : {"font_color" : "#48d1cc"},
        "f-mediumvioletred"         : {"font_color" : "#c71585"},
        "f-midnightblue"            : {"font_color" : "#191970"},
        "f-mintcream"               : {"font_color" : "#f5fffa"},
        "f-mistyrose"               : {"font_color" : "#ffe4e1"},
        "f-moccasin"                : {"font_color" : "#ffe4b5"},
        "f-navajowhite"             : {"font_color" : "#ffdead"},
        "f-navy"                    : {"font_color" : "#000080"},
        "f-oldlace"                 : {"font_color" : "#fdf5e6"},
        "f-olive"                   : {"font_color" : "#808000"},
        "f-olivedrab"               : {"font_color" : "#6b8e23"},
        "f-orange"                  : {"font_color" : "#ffa500"},
        "f-orangered"               : {"font_color" : "#ff4500"},
        "f-orchid"                  : {"font_color" : "#da70d6"},
        "f-palegoldenrod"           : {"font_color" : "#eee8aa"},
        "f-palegreen"               : {"font_color" : "#98fb98"},
        "f-paleturquoise"           : {"font_color" : "#afeeee"},
        "f-palevioletred"           : {"font_color" : "#db7093"},
        "f-papayawhip"              : {"font_color" : "#ffefd5"},
        "f-peachpuff"               : {"font_color" : "#ffdab9"},
        "f-peru"                    : {"font_color" : "#cd853f"},
        "f-pink"                    : {"font_color" : "#ffc0cb"},
        "f-plum"                    : {"font_color" : "#dda0dd"},
        "f-powderblue"              : {"font_color" : "#b0e0e6"},
        "f-purple"                  : {"font_color" : "#800080"},
        "f-red"                     : {"font_color" : "#ff0000"},
        "f-rosybrown"               : {"font_color" : "#bc8f8f"},
        "f-royalblue"               : {"font_color" : "#4169e1"},
        "f-saddlebrown"             : {"font_color" : "#8b4513"},
        "f-salmon"                  : {"font_color" : "#fa8072"},
        "f-sandybrown"              : {"font_color" : "#f4a460"},
        "f-seagreen"                : {"font_color" : "#2e8b57"},
        "f-seashell"                : {"font_color" : "#fff5ee"},
        "f-sienna"                  : {"font_color" : "#a0522d"},
        "f-silver"                  : {"font_color" : "#c0c0c0"},
        "f-skyblue"                 : {"font_color" : "#87ceeb"},
        "f-slateblue"               : {"font_color" : "#6a5acd"},
        "f-slategray"               : {"font_color" : "#708090"},
        "f-slategrey"               : {"font_color" : "#708090"},
        "f-snow"                    : {"font_color" : "#fffafa"},
        "f-springgreen"             : {"font_color" : "#00ff7f"},
        "f-steelblue"               : {"font_color" : "#4682b4"},
        "f-tan"                     : {"font_color" : "#d2b48c"},
        "f-teal"                    : {"font_color" : "#008080"},
        "f-thistle"                 : {"font_color" : "#d8bfd8"},
        "f-tomato"                  : {"font_color" : "#ff6347"},
        "f-turquoise"               : {"font_color" : "#40e0d0"},
        "f-violet"                  : {"font_color" : "#ee82ee"},
        "f-wheat"                   : {"font_color" : "#f5deb3"},
        "f-white"                   : {"font_color" : "#ffffff"},
        "f-whitesmoke"              : {"font_color" : "#f5f5f5"},
        "f-yellow"                  : {"font_color" : "#ffff00"},
        "f-yellowgreen"             : {"font_color" : "#9acd32"},

        # background color
        "b-aliceblue"               : {"bg_color" : "#f0f8ff"},
        "b-antiquewhite"            : {"bg_color" : "#faebd7"},
        "b-aqua"                    : {"bg_color" : "#00ffff"},
        "b-aquamarine"              : {"bg_color" : "#7fffd4"},
        "b-azure"                   : {"bg_color" : "#f0ffff"},
        "b-beige"                   : {"bg_color" : "#f5f5dc"},
        "b-bisque"                  : {"bg_color" : "#ffe4c4"},
        "b-black"                   : {"bg_color" : "#000000"},
        "b-blanchedalmond"          : {"bg_color" : "#ffebcd"},
        "b-blue"                    : {"bg_color" : "#0000ff"},
        "b-blueviolet"              : {"bg_color" : "#8a2be2"},
        "b-brown"                   : {"bg_color" : "#a52a2a"},
        "b-burlywood"               : {"bg_color" : "#deb887"},
        "b-cadetblue"               : {"bg_color" : "#5f9ea0"},
        "b-chartreuse"              : {"bg_color" : "#7fff00"},
        "b-chocolate"               : {"bg_color" : "#d2691e"},
        "b-coral"                   : {"bg_color" : "#ff7f50"},
        "b-cornflowerblue"          : {"bg_color" : "#6495ed"},
        "b-cornsilk"                : {"bg_color" : "#fff8dc"},
        "b-crimson"                 : {"bg_color" : "#dc143c"},
        "b-cyan"                    : {"bg_color" : "#00ffff"},
        "b-darkblue"                : {"bg_color" : "#00008b"},
        "b-darkcyan"                : {"bg_color" : "#008b8b"},
        "b-darkgoldenrod"           : {"bg_color" : "#b8860b"},
        "b-darkgray"                : {"bg_color" : "#a9a9a9"},
        "b-darkgreen"               : {"bg_color" : "#006400"},
        "b-darkgrey"                : {"bg_color" : "#a9a9a9"},
        "b-darkkhaki"               : {"bg_color" : "#bdb76b"},
        "b-darkmagenta"             : {"bg_color" : "#8b008b"},
        "b-darkolivegreen"          : {"bg_color" : "#556b2f"},
        "b-darkorange"              : {"bg_color" : "#ff8c00"},
        "b-darkorchid"              : {"bg_color" : "#9932cc"},
        "b-darkred"                 : {"bg_color" : "#8b0000"},
        "b-darksalmon"              : {"bg_color" : "#e9967a"},
        "b-darkseagreen"            : {"bg_color" : "#8fbc8f"},
        "b-darkslateblue"           : {"bg_color" : "#483d8b"},
        "b-darkslategray"           : {"bg_color" : "#2f4f4f"},
        "b-darkslategrey"           : {"bg_color" : "#2f4f4f"},
        "b-darkturquoise"           : {"bg_color" : "#00ced1"},
        "b-darkviolet"              : {"bg_color" : "#9400d3"},
        "b-deeppink"                : {"bg_color" : "#ff1493"},
        "b-deepskyblue"             : {"bg_color" : "#00bfff"},
        "b-dimgray"                 : {"bg_color" : "#696969"},
        "b-dimgrey"                 : {"bg_color" : "#696969"},
        "b-dodgerblue"              : {"bg_color" : "#1e90ff"},
        "b-firebrick"               : {"bg_color" : "#b22222"},
        "b-floralwhite"             : {"bg_color" : "#fffaf0"},
        "b-forestgreen"             : {"bg_color" : "#228b22"},
        "b-fuchsia"                 : {"bg_color" : "#ff00ff"},
        "b-gainsboro"               : {"bg_color" : "#dcdcdc"},
        "b-ghostwhite"              : {"bg_color" : "#f8f8ff"},
        "b-gold"                    : {"bg_color" : "#ffd700"},
        "b-goldenrod"               : {"bg_color" : "#daa520"},
        "b-gray"                    : {"bg_color" : "#808080"},
        "b-green"                   : {"bg_color" : "#008000"},
        "b-greenyellow"             : {"bg_color" : "#adff2f"},
        "b-grey"                    : {"bg_color" : "#808080"},
        "b-honeydew"                : {"bg_color" : "#f0fff0"},
        "b-hotpink"                 : {"bg_color" : "#ff69b4"},
        "b-indianred"               : {"bg_color" : "#cd5c5c"},
        "b-indigo"                  : {"bg_color" : "#4b0082"},
        "b-ivory"                   : {"bg_color" : "#fffff0"},
        "b-khaki"                   : {"bg_color" : "#f0e68c"},
        "b-lavender"                : {"bg_color" : "#e6e6fa"},
        "b-lavenderblush"           : {"bg_color" : "#fff0f5"},
        "b-lawngreen"               : {"bg_color" : "#7cfc00"},
        "b-lemonchiffon"            : {"bg_color" : "#fffacd"},
        "b-lightblue"               : {"bg_color" : "#add8e6"},
        "b-lightcoral"              : {"bg_color" : "#f08080"},
        "b-lightcyan"               : {"bg_color" : "#e0ffff"},
        "b-lightgoldenrodyellow"    : {"bg_color" : "#fafad2"},
        "b-lightgray"               : {"bg_color" : "#d3d3d3"},
        "b-lightgreen"              : {"bg_color" : "#90ee90"},
        "b-lightgrey"               : {"bg_color" : "#d3d3d3"},
        "b-lightpink"               : {"bg_color" : "#ffb6c1"},
        "b-lightsalmon"             : {"bg_color" : "#ffa07a"},
        "b-lightseagreen"           : {"bg_color" : "#20b2aa"},
        "b-lightskyblue"            : {"bg_color" : "#87cefa"},
        "b-lightslategray"          : {"bg_color" : "#778899"},
        "b-lightslategrey"          : {"bg_color" : "#778899"},
        "b-lightsteelblue"          : {"bg_color" : "#b0c4de"},
        "b-lightyellow"             : {"bg_color" : "#ffffe0"},
        "b-lime"                    : {"bg_color" : "#00ff00"},
        "b-limegreen"               : {"bg_color" : "#32cd32"},
        "b-linen"                   : {"bg_color" : "#faf0e6"},
        "b-magenta"                 : {"bg_color" : "#ff00ff"},
        "b-maroon"                  : {"bg_color" : "#800000"},
        "b-mediumaquamarine"        : {"bg_color" : "#66cdaa"},
        "b-mediumblue"              : {"bg_color" : "#0000cd"},
        "b-mediumorchid"            : {"bg_color" : "#ba55d3"},
        "b-mediumpurple"            : {"bg_color" : "#9370db"},
        "b-mediumseagreen"          : {"bg_color" : "#3cb371"},
        "b-mediumslateblue"         : {"bg_color" : "#7b68ee"},
        "b-mediumspringgreen"       : {"bg_color" : "#00fa9a"},
        "b-mediumturquoise"         : {"bg_color" : "#48d1cc"},
        "b-mediumvioletred"         : {"bg_color" : "#c71585"},
        "b-midnightblue"            : {"bg_color" : "#191970"},
        "b-mintcream"               : {"bg_color" : "#f5fffa"},
        "b-mistyrose"               : {"bg_color" : "#ffe4e1"},
        "b-moccasin"                : {"bg_color" : "#ffe4b5"},
        "b-navajowhite"             : {"bg_color" : "#ffdead"},
        "b-navy"                    : {"bg_color" : "#000080"},
        "b-oldlace"                 : {"bg_color" : "#fdf5e6"},
        "b-olive"                   : {"bg_color" : "#808000"},
        "b-olivedrab"               : {"bg_color" : "#6b8e23"},
        "b-orange"                  : {"bg_color" : "#ffa500"},
        "b-orangered"               : {"bg_color" : "#ff4500"},
        "b-orchid"                  : {"bg_color" : "#da70d6"},
        "b-palegoldenrod"           : {"bg_color" : "#eee8aa"},
        "b-palegreen"               : {"bg_color" : "#98fb98"},
        "b-paleturquoise"           : {"bg_color" : "#afeeee"},
        "b-palevioletred"           : {"bg_color" : "#db7093"},
        "b-papayawhip"              : {"bg_color" : "#ffefd5"},
        "b-peachpuff"               : {"bg_color" : "#ffdab9"},
        "b-peru"                    : {"bg_color" : "#cd853f"},
        "b-pink"                    : {"bg_color" : "#ffc0cb"},
        "b-plum"                    : {"bg_color" : "#dda0dd"},
        "b-powderblue"              : {"bg_color" : "#b0e0e6"},
        "b-purple"                  : {"bg_color" : "#800080"},
        "b-red"                     : {"bg_color" : "#ff0000"},
        "b-rosybrown"               : {"bg_color" : "#bc8f8f"},
        "b-royalblue"               : {"bg_color" : "#4169e1"},
        "b-saddlebrown"             : {"bg_color" : "#8b4513"},
        "b-salmon"                  : {"bg_color" : "#fa8072"},
        "b-sandybrown"              : {"bg_color" : "#f4a460"},
        "b-seagreen"                : {"bg_color" : "#2e8b57"},
        "b-seashell"                : {"bg_color" : "#fff5ee"},
        "b-sienna"                  : {"bg_color" : "#a0522d"},
        "b-silver"                  : {"bg_color" : "#c0c0c0"},
        "b-skyblue"                 : {"bg_color" : "#87ceeb"},
        "b-slateblue"               : {"bg_color" : "#6a5acd"},
        "b-slategray"               : {"bg_color" : "#708090"},
        "b-slategrey"               : {"bg_color" : "#708090"},
        "b-snow"                    : {"bg_color" : "#fffafa"},
        "b-springgreen"             : {"bg_color" : "#00ff7f"},
        "b-steelblue"               : {"bg_color" : "#4682b4"},
        "b-tan"                     : {"bg_color" : "#d2b48c"},
        "b-teal"                    : {"bg_color" : "#008080"},
        "b-thistle"                 : {"bg_color" : "#d8bfd8"},
        "b-tomato"                  : {"bg_color" : "#ff6347"},
        "b-turquoise"               : {"bg_color" : "#40e0d0"},
        "b-violet"                  : {"bg_color" : "#ee82ee"},
        "b-wheat"                   : {"bg_color" : "#f5deb3"},
        "b-white"                   : {"bg_color" : "#ffffff"},
        "b-whitesmoke"              : {"bg_color" : "#f5f5f5"},
        "b-yellow"                  : {"bg_color" : "#ffff00"},
        "b-yellowgreen"             : {"bg_color" : "#9acd32"},

        # font size
        "f-1"        : {"font_size": 1},
        "f-2"        : {"font_size": 2},
        "f-3"        : {"font_size": 3},
        "f-4"        : {"font_size": 4},
        "f-5"        : {"font_size": 5},
        "f-6"        : {"font_size": 6},
        "f-7"        : {"font_size": 7},
        "f-8"        : {"font_size": 8},
        "f-9"        : {"font_size": 9},
        "f-10"       : {"font_size": 10},
        "f-11"       : {"font_size": 11},
        "f-12"       : {"font_size": 12},
        "f-13"       : {"font_size": 13},
        "f-14"       : {"font_size": 14},
        "f-15"       : {"font_size": 15},
        "f-16"       : {"font_size": 16},
        "f-17"       : {"font_size": 17},
        "f-18"       : {"font_size": 18},
        "f-19"       : {"font_size": 19},
        "f-20"       : {"font_size": 20},
        "f-21"       : {"font_size": 21},
        "f-22"       : {"font_size": 22},
        "f-23"       : {"font_size": 23},
        "f-24"       : {"font_size": 24},
        "f-25"       : {"font_size": 25},
        "f-26"       : {"font_size": 26},
        "f-27"       : {"font_size": 27},
        "f-28"       : {"font_size": 28},
        "f-29"       : {"font_size": 29},
        "f-30"       : {"font_size": 30},
        "f-31"       : {"font_size": 31},
        "f-32"       : {"font_size": 32},
        "f-33"       : {"font_size": 33},
        "f-34"       : {"font_size": 34},
        "f-35"       : {"font_size": 35},
        "f-36"       : {"font_size": 36},
        "f-37"       : {"font_size": 37},
        "f-38"       : {"font_size": 38},
        "f-39"       : {"font_size": 39},
        "f-40"       : {"font_size": 40},
        "f-41"       : {"font_size": 41},
        "f-42"       : {"font_size": 42},
        "f-43"       : {"font_size": 43},
        "f-44"       : {"font_size": 44},
        "f-45"       : {"font_size": 45},
        "f-46"       : {"font_size": 46},
        "f-47"       : {"font_size": 47},
        "f-48"       : {"font_size": 48},
        "f-49"       : {"font_size": 49},
        "f-50"       : {"font_size": 50},
        "f-51"       : {"font_size": 51},
        "f-52"       : {"font_size": 52},
        "f-53"       : {"font_size": 53},
        "f-54"       : {"font_size": 54},
        "f-55"       : {"font_size": 55},
        "f-56"       : {"font_size": 56},
        "f-57"       : {"font_size": 57},
        "f-58"       : {"font_size": 58},
        "f-59"       : {"font_size": 59},
        "f-60"       : {"font_size": 60},
        "f-61"       : {"font_size": 61},
        "f-62"       : {"font_size": 62},
        "f-63"       : {"font_size": 63},
        "f-64"       : {"font_size": 64},
        "f-65"       : {"font_size": 65},
        "f-66"       : {"font_size": 66},
        "f-67"       : {"font_size": 67},
        "f-68"       : {"font_size": 68},
        "f-69"       : {"font_size": 69},
        "f-70"       : {"font_size": 70},
        "f-71"       : {"font_size": 71},
        "f-72"       : {"font_size": 72},
        "f-73"       : {"font_size": 73},
        "f-74"       : {"font_size": 74},
        "f-75"       : {"font_size": 75},
        "f-76"       : {"font_size": 76},
        "f-77"       : {"font_size": 77},
        "f-78"       : {"font_size": 78},
        "f-79"       : {"font_size": 79},
        "f-80"       : {"font_size": 80},
        "f-81"       : {"font_size": 81},
        "f-82"       : {"font_size": 82},
        "f-83"       : {"font_size": 83},
        "f-84"       : {"font_size": 84},
        "f-85"       : {"font_size": 85},
        "f-86"       : {"font_size": 86},
        "f-87"       : {"font_size": 87},
        "f-88"       : {"font_size": 88},
        "f-89"       : {"font_size": 89},
        "f-90"       : {"font_size": 90},
        "f-91"       : {"font_size": 91},
        "f-92"       : {"font_size": 92},
        "f-93"       : {"font_size": 93},
        "f-94"       : {"font_size": 94},
        "f-95"       : {"font_size": 95},
        "f-96"       : {"font_size": 96},
        "f-97"       : {"font_size": 97},
        "f-98"       : {"font_size": 98},
        "f-99"       : {"font_size": 99},
        "f-100"      : {"font_size": 100},
        "f-101"      : {"font_size": 101},
        "f-102"      : {"font_size": 102},
        "f-103"      : {"font_size": 103},
        "f-104"      : {"font_size": 104},
        "f-105"      : {"font_size": 105},
        "f-106"      : {"font_size": 106},
        "f-107"      : {"font_size": 107},
        "f-108"      : {"font_size": 108},
        "f-109"      : {"font_size": 109},
        "f-110"      : {"font_size": 110},
        "f-111"      : {"font_size": 111},
        "f-112"      : {"font_size": 112},
        "f-113"      : {"font_size": 113},
        "f-114"      : {"font_size": 114},
        "f-115"      : {"font_size": 115},
        "f-116"      : {"font_size": 116},
        "f-117"      : {"font_size": 117},
        "f-118"      : {"font_size": 118},
        "f-119"      : {"font_size": 119},
        "f-120"      : {"font_size": 120},
        "f-121"      : {"font_size": 121},
        "f-122"      : {"font_size": 122},
        "f-123"      : {"font_size": 123},
        "f-124"      : {"font_size": 124},
        "f-125"      : {"font_size": 125},
        "f-126"      : {"font_size": 126},
        "f-127"      : {"font_size": 127},
        "f-128"      : {"font_size": 128},
        "f-129"      : {"font_size": 129},
        "f-130"      : {"font_size": 130},
        "f-131"      : {"font_size": 131},
        "f-132"      : {"font_size": 132},
        "f-133"      : {"font_size": 133},
        "f-134"      : {"font_size": 134},
        "f-135"      : {"font_size": 135},
        "f-136"      : {"font_size": 136},
        "f-137"      : {"font_size": 137},
        "f-138"      : {"font_size": 138},
        "f-139"      : {"font_size": 139},
        "f-140"      : {"font_size": 140},
        "f-141"      : {"font_size": 141},
        "f-142"      : {"font_size": 142},
        "f-143"      : {"font_size": 143},
        "f-144"      : {"font_size": 144},
        "f-145"      : {"font_size": 145},
        "f-146"      : {"font_size": 146},
        "f-147"      : {"font_size": 147},
        "f-148"      : {"font_size": 148},
        "f-149"      : {"font_size": 149},
        "f-150"      : {"font_size": 150},



        }

#-------------------------------------------

builds= {
        "CENTER":["center","vcenter"],
        "note_1":["bold","f-blue"],
        "note_2":["bold","f-red"],
        "note_3":["bold","f-red",{"font_color":"green"}],
        "cell"  :["bold","italic","f-12","f-darkblue","box2","l-red"],

        }


if __name__=="__main__": print("ok")

